fix(adapter): fix undefined reference to hasBrowserEnv
hasBrowserEnv is defined in lib/platform, and not lib/utils.
Because of this, the base URL was not defaulting to the origin
(window.location.href) in browser environments.

This bug was introduced in #6543.

Signed-off-by: Antonin Bas <antonin.bas@broadcom.com>