Fixing possible runtime error in isAxiosError.js type guard
AxiosError type guard can cause runtime error if payload is a `null`, since `null` also passes the check `typeof payload === 'object'`. Then the code cannot access `.isAxiosError` of a `null`.

```
TypeError: Cannot read property 'isAxiosError' of null
```